### ISSUE TITLE
Cannot install 4.1.3 or later (.Net 7 SDK Web project)

### ISSUE THREAD

**Issue by gaelj** [jamesmh/coravel#336] opened 2023-07-06 09:25 UTC
**Describe the bug**

I am trying to use Coravel non-pro (for the first time ever) in a .Net 7.0.304 SDK Web project.
FYI I use a self-hosted Baget instance as a Nuget cache, which works perfectly with all other packages.

- `dotnet add package Coravel` fails with `error: Value cannot be null. (Parameter 'version')`
- adding the package manually in the csproj and runnning `dotnet restore --no-cache` fails with `/usr/share/dotnet/sdk/7.0.304/NuGet.targets(156,5): error MSB4181: The "RestoreTask" task returned false but did not log an error.`
- the problem doesn't happen if I reference the old version `4.1.2`. Any version above fails.
- I primarily develop on Linux / VS Code / CLI, but the problem is identical on Windows

**Affected Coravel Feature**

Installation fails, so no features are available at all.

**Expected behaviour**

There should be no error when adding / restoring the Nuget package.

**Comment by jamesmh** [comment] 2023-08-17 01:56
Just trying this out and cannot reproduce it. Will close this but let me know if you still have issues: perhaps using .NET 7.0.400 will work for you?

![image](https://github.com/jamesmh/coravel/assets/7213174/5449af01-8c6a-466d-b5c5-c003ef702c68)

**Closed by jamesmh** 2023-08-17 01:56 UTC
